services:
  crmwebhook:
    build:
      context: .
    image: crmwebhook:v1.2
    container_name: crmwebhook
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    command: python run.py
